### ISSUE TITLE
python script error

### ISSUE THREAD

**Issue by kwitherstine** [CumulusNetworks/cldemo-config-routing#11]
When running the python script, getting the following error:

spine02: sudo reboot
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "pushconfig.py", line 17, in go
    expect.connect(host, username="cumulus", password="CumulusLinux!")
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 311, in connect
    raise NoValidConnectionsError(errors)
NoValidConnectionsError: [Errno None] Unable to connect to port 22 on  or 192.168.0.32
^@Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "pushconfig.py", line 17, in go
    expect.connect(host, username="cumulus", password="CumulusLinux!")
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 292, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/util.py", line 270, in retry_on_signal
    return function()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 292, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 110] Connection timed out

**Comment by ericpulvino** [comment]
I confirm this issue. I can see that certain devices do not seem to receive DHCP leases. Will dig in further next week.

**Comment by ericpulvino** [comment]
I recant my earlier statement I can't seem to reproduce this. I thought I had earlier because I had two simulations running simultaneously and they were interfering with one another.

If you're still seeing this issue and can reproduce it, let me know and we can debug it.

**Comment by isharacomix** [comment]
This happens when a server dies during the reboot process. Nondeterministically, a reboot command will make virtualbox end with the VM in an ABORT state.

**Comment by isharacomix** [comment]
Also, I've applied a new fix that uses ifreload instead of reboot, which may make this happen less. I'm going to close for now, but please reopen if you encounter it again!
